[platformio]
default_envs = esp32-s3-test

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
  -Wall
  -Wextra

[env:esp32-s3-test]
build_flags =
  ${env.build_flags}
  -DTEST_MODE=1

[env:esp32-s3-hardware]
build_flags =
  ${env.build_flags}
  -DTEST_MODE=0
